### DISCUSSION TITLE
Explore K8s Controller

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#11] [Explore / Experiment]
```yaml
- https://arxiv.org/pdf/2209.01077.pdf
- Adapting K8s controllers to the edge: On demand control planes for the WASM & WASI
  - Why should k8s controllers be long lived?
  - Dispersion of cloud to fog, edge & IOT
  - a browser tech designed as a portable binary code format
- Main Design:
  - Parent & Child operators
  - Child operators run as WASM instances in the WASM runtime embedded in the parent operator
  - All child operators run in the same process as the parent operator
  - This process runs inside a single container in a single Kubernetes pod
  - Isolation is provided by the WASM engine, eliminating the overhead due to container isolation
  - The WASM runtime makes it possible to add or remove child operators without interfering with the other active child operators
  - The parent operator extends the WASM runtime with host functions 
  - These functions can be used by the child operators to communicate with the Kubernetes API
  - Low-level operator logic is moved to the parent operator
  - This reduces the complexity and overhead of the client operators
  - Can dynamically unload inactive operators
- Efficiency & Async
  - In order to efficiently make Kubernetes API requests, the child operators should perform them asynchronously
  - Existing WASM runtimes offer no support for asynchronous calls
  - A new solution was implemented to support asynchronous operations to the WASM runtime (embedded in parent operator) 
  - By extending the WASM runtime, the child operators wait for host functions asynchronously
- Parent Operator
  - WASM engine
  - Host functions exposed to the WASM runtime
  - Work queue
```

```yaml
- Best Practices
  - spec.generation vs status.observedGeneration
    - https://alenkacz.medium.com/kubernetes-operator-best-practices-implementing-observedgeneration-250728868792
  - 
```

```yaml
- https://github.com/kube-bind/kube-bind
- https://github.com/kubernetes-sigs/logical-cluster
```
