### DISCUSSION TITLE
Explore Repro-Get

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#13] [Explore / Experiment]
```yaml
- # Talk
- https://fosdem.org/2023/schedule/event/container_reproducible_dockerfile/
  - bit-by-bit reproducibility, deterministic, timestamped
  - Reproducibility has to be attestable by anybody at anytime
  - Buildkit v0.11 supports reproducible timestamps
    - Conforms to https://reproducible-builds.org/specs/source-date-epoch
  - Important Notes:
    - Can be used in non container environments
    - repro-get needs buildkit v0.11.0
    - The filesystem (ext4) & Ubuntu (22.04) should be pinned as well
  - Example
    - ./hack/test-dockerfile-repro.sh examples-gcc
```

```yaml
- # Setup
  - limactl start ubuntu
  - limactl shell ubuntu
  - uname -a
  - sudo apt install make
  - # Install golang (look for exact arch)
    - refer: https://go.dev/dl/
    - refer: https://go.dev/doc/install
  - sudo apt install docker.io
  - git clone git@github.com:reproducible-containers/repro-get.git
  - cd repro-get
  - # Build & Install repro-get
    - make
    - sudo make install
  - # Verify
    - repro-get
  - exit
```

```yaml
- # Install
  - # use details like SHA & artifact location from this output to feed `repro-get` to install hello
    - apt-cache show hello # 😍 🚀
  - # Even simpler alternative to generate install file for hello
    - repro-get hash generate hello >SHA256SUMS-arm64-hello
  - # Create file with all installed packages
    - repro-get hash generate >SHA256SUMS-arm64-all
```
