### DISCUSSION TITLE
Handmade Distroless

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#18] [Explore / Experiment]
### 🐌 Build Some Distroless Images

**Comment by AmitKumarDas** [comment]
### Build You a Distroless Image

```yaml
- Til: Actions performed on image layers during upload
- Hint: Digest, Size, Diffid
- Refer: https://github.com/google/go-containerregistry/issues/1549
```

```yaml
- Til: Minimal in-memory OCI registry
- Refer: 
  - https://github.com/google/go-containerregistry/issues/1579
  - https://github.com/chainguard-dev/actions/tree/main/setup-registry
```

```yaml
- Show: Flatten the layers of an image
- Refer: https://github.com/google/go-containerregistry/issues/1590
```

```yaml
- Show: Build container image using various args & DOCKER_BUILDKIT
- Refer: https://github.com/grafana/grafana/blob/main/Makefile
- Query: Why the need for a tmp folder?
```

```yaml
- How: Use shell to setup a non root user before removing the shell itself
- Refer: https://alexos.dev/2022/07/08/creating-an-up-to-date-distroless-python-image/
```

```yaml
- What: Use Distroless cc instead if base to build Python apps
- Refer:
  - https://alexos.dev/2022/07/08/creating-an-up-to-date-distroless-python-image/
  - https://github.com/GoogleContainerTools/distroless/tree/main/cc
```

```yaml
- Note: Google distroless may not fix CRITICAL CVE if not fixed at upstream
- Refer: https://github.com/GoogleContainerTools/distroless/issues/1003
```

```yaml
- How: Build Distroless image for simple Py application
- Refer: https://github.com/GoogleContainerTools/distroless/blob/main/examples/python3/Dockerfile
```

```yaml
- What: Steps before placing a C Py app on Distroless Python
- Til:
  - Install python3-venv for the built-in Python3 venv module
  - Install gcc libpython3-dev to compile C Python modules
  - Update pip setuputils and wheel to build new packages
- Refer: 
  - https://github.com/GoogleContainerTools/distroless/blob/main/examples/python3-requirements/Dockerfile
```

```yaml
- What: Rate limiting led to dropping .NET from Distroless
- Refer: https://github.com/GoogleContainerTools/distroless/issues/710
```

```yaml
- Fix:
  - HTTPS support
  - Timezone support
  - Named port resolution
  - Library for project binaries that cannot be statically built
- Refer: https://github.com/prometheus/busybox/blob/master/glibc/Dockerfile
```

```yaml
- What: Deep dive into Distroless .NET core
- Refer: https://github.com/GoogleContainerTools/distroless/issues/512
```

```yaml
- What: Learn more about Java & building container images for it
- Refer: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md
```

```yaml
- How: 
  - Build debian based pprofweb & package on top of Distroless
  - Run as nobody user i.e. non root 
- Refer: https://github.com/evanj/pprofweb/blob/master/Dockerfile
```

```yaml
- How: Custom build, patch & package a static curl based image
- Ans: 
  - https://github.com/tarampampam/curl-docker
  - https://github.com/moparisthebest/static-curl
```

```yaml
- What: Build a Distroless Ubuntu Image
- Refer: 
  - https://ubuntu.com/blog/craft-custom-chiselled-ubuntu-distroless
  - https://ubuntu.com/blog/combining-distroless-and-ubuntu-chiselled-containers
```

```yaml
- How: 
  - Build a Distroless image based on debian
  - Build Distroless for fluent-bit
  - Build Distroless for .NET
- Learn: Best practices while building an image:
  - sha512sum, Non Root, Remove man pages & docs
- Refer:
  - https://github.com/616b2f/distroless-dotnet/blob/main/Dockerfile
  - https://github.com/GoogleContainerTools/distroless/issues/863
  - https://github.com/fluent/fluent-bit/pull/4859/files
```

```yaml
- How: 
  - Scanners find installed debian packages
  - dpkg & tar work together
- Refer: https://github.com/GoogleContainerTools/distroless/issues/863
```

```yaml
- What:
  - Verify if TIMEZONE is set to UTC?
  - Does DNS work?
- Til: Testing via chroot within Dockerfile
- Refer:
  - https://github.com/docker-library/busybox/blob/master/latest/glibc/Dockerfile.builder
```
