### DISCUSSION TITLE
Explore WASM

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#23] [Explore / Experiment]
```yaml
- https://surma.dev/things/rust-to-webassembly/
- 
  - # Notes # General
    - Mostly WebAssembly modules take the role of a library 
    - Can be an executable in the context of WASI
    - 
  - # Troubleshoot
    - Inspect by converting a WebAssembly binary to WAT
    - To ensure compiler does not remove a function: add #[no_mangle] attribute
    - A quick way to inspect the innards of a WebAssembly module is llvm-objdump
    - Alternatively, wasm-objdump which is part of wabt
    - Twiggy excels at debugging the WASM size
    - 
  - # Notes # Memory Layout
    - Stick to types that map cleanly to WebAssembly types like i32 or f64
    - If you use higher-level types like arrays, slices, or even owned types like String
      - The function might end up with more parameters than they have in Rust
      - And generally requires a deeper understanding of memory layout
    - 
  - # Notes # ABIs
    - Even if Rust code is compiled to WebAssembly
    - Versions of Rust can emit a WebAssembly module with completely different fn signatures
    - 
  - # Parameters are passed from caller to callee 
    - As a pointer to a memory or as an immediate value
    - Is part of the Application Binary Interface definition, or “ABI” for short
    - rustc uses Rust’s ABI by default, which is not stable and mostly consider a Rust internal 🤨 👓
    - 
  - # SOLUTION: C ABIs
    - We can explicitly define which ABI we want rustc to use for a function
    - Via **extern** keyword
    - Inter-language function calls via the C ABI
    - The C ABI won’t change
    - Hence WebAssembly module interface won’t change either
    - 
  - # extern keyword vs extern block
    - extern blocks declare functions that compiler expects to provided by ”someone else” at link time
    - Same as linking against C libraries in Rust
    - External functions are always implicitly unsafe
    - 
  - # unsafe [TIP]
    - To avoid having to sprinkle unsafe { ... } everywhere
    - It is desirable to write wrapper functions that restore the safety invariants of Rust
    - Solution: INLINE MODULES
```
