### DISCUSSION TITLE
Build System for Secure Base Images

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#35] [Explore / Experiment]
### Thoughts
```yaml
- Developer Experience, Readability & Extensible: 
  - All three
- Declarative specs are input
- Declarative specs as plans
- Plans are predefined inputs
- Declarative specs in Rusty Object Notation
- Maybe wrap shell &/ external commands when required
- Can this be used as a bot by other projects?
- Understands git, branches, commits, & tags
- Interacts with OCI registry
- Bunch of CLIs
- Use Dockerfile to download these CLIs?
- Use Dockerfile to build these CLIs?
- Can SBOM provide these insights?
- Can SBOM provide any insights?
- Understand how vulnerability database works?
- Understand how vulnerability scanners work?
- Research on Fuzzing?
```

### Needs
```yaml
- Top 5 images with most number of CVEs
- Top 5 images with most number of CRITICAL CVEs
- Top 2 languages with most number of CVEs
- Top 2 languages with most number of CRITICAL CVEs
- Top 5 images with most number of runtime dependencies
- List of all distros used to build images
- Top 3 distros with most number of images
- Top 3 distros with most number of CVEs
- Top 10 images based on its size

```

### Read
```yaml
- Day 1:
  - https://google.github.io/comprehensive-rust/welcome.html # WIP
  - https://github.com/DeterminateSystems/riff # WIP
  - https://github.com/ron-rs/ron # WIP
  - https://doc.rust-lang.org/cargo/reference/build-script-examples.html # WIP
  - https://doc.rust-lang.org/cargo/reference/build-scripts.html # WIP
- Day 2:
  - https://jakobwaibel.com/2022/06/06/ptrace/
  - https://github.com/bwplotka/bingo
- 
- https://github.com/benchkram/bob/ # Go & Nix together
- https://github.com/yaxitech/ragenix # Rust & Nix together
- https://github.com/nlewo/nix2container # Go & Nix & Docker
- https://github.com/cachix/devenv # Nix & Bash
- https://github.com/tazjin/nixery # Nix & Go & Bash
- https://github.com/DeterminateSystems/nix-installer # ADVANCED
- https://floxdev.com/blog/flox-and-containers # Nix & Container
- https://blog.kubesimplify.com/bake-your-container-images-with-bake
- https://www.howtogeek.com/devops/
  - how-to-use-docker-buildx-bake-to-create-complex-image-build-pipelines/
- https://github.com/nix-community/nix-init # NIX  & RUST
- https://github.com/rust-shell-script/rust_cmd_lib # bash in rust
- https://docs.rs/xtask-watch/latest/xtask_watch/
- https://crates.io/crates/xtask-wasm
```

**Comment by AmitKumarDas** [comment]
### Detour
- Involves Learning Rust In Interesting Ways
- This Includes Understanding by Reading Existing Codebases
- These sections may be considered as 101

```yaml
- What: Tools to install before we begin
- Refer: https://google.github.io/comprehensive-rust/cargo/rust-ecosystem.html
```

```yaml
- What:
  - Expose modules for your project
  - Define your own type e.g. type system for shell commands
  - Define typed subcommands for your CLI
- How: https://github.com/DeterminateSystems/riff/blob/main/src/cmds/mod.rs
```

```yaml
- TIL: Rust uses macros for variadic arguments
- Why: Rust does not support operator overloading
- Refer: https://google.github.io/comprehensive-rust/hello-world.html
```

```yaml
- What: Simple techniques to Deserialise
- Hint: RON, Parse vs. Deserialise, Serialise
- Mnemonic: 
  - Serialise is to_string (S-matters) 
  - While deserialise is from_string
- Refer: 
  - https://github.com/ron-rs/ron/blob/master/examples/decode.rs
  - https://github.com/ron-rs/ron/blob/master/examples/decode_file.rs
  - https://github.com/ron-rs/ron/blob/master/examples/transcode.rs
```

```yaml
- Til: Panic is a controlled crash of the program
- Note:
  - You get panics in debug mode
  - You get wrap arounds in release mode
- Refer: https://google.github.io/comprehensive-rust/why-rust/runtime.html
```

```yaml
- Til: Rust enums are ‘Algebraic Data Types’, also known as SUM TYPES
- Note: This allow the type system to express things like Option<T> and Result<T, E>
- Refer: https://google.github.io/comprehensive-rust/why-rust/modern.html
```

```yaml
- What: 
  - Types vs Literals
  - Strings vs Byte Strings
  - Rust strings are UTF-8 encoded and can contain any Unicode character
  - Compound Types such as Arrays & Tuples
- Refer:
  - https://google.github.io/comprehensive-rust/hello-world.html
  - https://google.github.io/comprehensive-rust/basic-syntax/scalar-types.html
  - https://google.github.io/comprehensive-rust/basic-syntax/compound-types.html
```

```yaml
- What: Println! formats
- Options:
  - {} gives the default output
    - {a} is also fine if we do not specify the variable after format string
  - {:?} gives the debug output
    - {a:?} is also fine if we do not specify the variable after format string
  - {a:#?} gives the pretty print output
- Refer: https://google.github.io/comprehensive-rust/basic-syntax/compound-types.html
```

```yaml
- What: Empty tuple i.e. () is also known as unit type
- What: () is both a type & the only valid value of that type
- Note: 
  - Both type & its value are expressed as ()
  - Used to indicate if a function or expression has no return value
  - Similar to void from other languages
- Refer:
  - https://google.github.io/comprehensive-rust/basic-syntax/compound-types.html
```

```yaml
- What: Reference in Rust
- Ans: A reference is said to “borrow” the value it refers to
- Note: Rust tracks the lifetimes of all references to ensure they live long enough
- Refer: 
  - https://google.github.io/comprehensive-rust/basic-syntax/references-dangling.html
```

```yaml
- What: let mut ref_x: &i32 and let ref_x: &mut i32
- Ans:
  - First one represents a mutable reference which can be bound to different values
  - Second represents a reference to a mutable value
- Refer: https://google.github.io/comprehensive-rust/basic-syntax/references.html
```

```yaml
- What: Slices is just a borrow & two dots i.e. &[..]
- Info:
  - &a[0..a.len()] is same as &a[..a.len()]
  - &a[2..a.len()] is same as &a[2..]
  - &a[0..a.len()] is same as &a[..]
- Imp: 
  - Memory safety prevents modifying the backing array after you created a slice
- Refer: https://google.github.io/comprehensive-rust/basic-syntax/slices.html
```

```yaml
- Why: Slice does not have a size
- Ans: It allows performing computations on slices of different sizes
- Refer: https://google.github.io/comprehensive-rust/basic-syntax/slices.html
```

```yaml
- What: &str vs. String
- Ans:
  - &str is an immutable reference to a string slice
  - String is a mutable string buffer
  - String literals are stored in the program's binary
  - String is a wrapper around vector of bytes
  - String is owned like a Vec<T>
  - String::from() creates a String from a string literal
  - format!() macro generates an owned String from dynamic values
  - You can borrow &str slices from String
- Refer: https://google.github.io/comprehensive-rust/basic-syntax/string-slices.html
```

```yaml
- What: Include the upper bound by using = sign
- Syntax: for i in 1..=n
- Refer: https://google.github.io/comprehensive-rust/basic-syntax/functions.html
```

```yaml
- TASK:
  - Fill STRUCT from command OUTPUT
  - Use REGEX to grep
  - Redirect stderr and stdout to same file
- Refer:
  - https://rust-lang-nursery.github.io/rust-cookbook/about.html
  - https://rust-lang-nursery.github.io/rust-cookbook/os/external.html
```
