### DISCUSSION TITLE
Experience Report: Nginx Distroless Image

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#37] [Explore / Experiment]
### References
```yaml
- https://medium.com/@rockmetoo/smallest-distroless-nginx-container-alpine-c08c3a9cac93
- https://spack.readthedocs.io/en/latest/package_list.html
- https://github.com/fluent/fluent-bit/tree/master/dockerfiles
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ # manifest # buildx
```

#### 😌 Just 3 Files to Distroless
```yaml
- Dockerfile
- nginx.conf # custom config to override the default
- www.conf # own domain/proxy configuration
```

#### 🏃‍♂️ Steps
```yaml
- Use multistage Dockerfile with following bases:
  - debian:latest
  - gcr.io/distroless/base-debian11
- Install the build dependencies
- Download source code
- Configure && make && make install
- Copy shared dependencies between the bases
- Create required nginx folders
- Overwrite nginx config files with yours
```

#### 😌 Just 3 Files to Distroless
```yaml
- Dockerfile
- nginx.conf # custom config to override the default
- www.conf # own domain/proxy configuration
```

#### 🏃‍♂️ Steps
```yaml
- Use multistage Dockerfile with following bases:
  - nginx:1.23.3
  - gcr.io/distroless/base-debian11
- Copy the shared dependencies between the bases
- Create required nginx folders
- Overwrite nginx config files with yours
```

### 7️⃣ Enterprise Capabilities
```yaml
- multiple compilers
- compile from source
- app version pinning
- compiler version pinning
- compile options
- target architectures
- granular control over direct & transitive dependencies
```

**Comment by AmitKumarDas** [comment]
### 👋 Useful Commands
```yaml
- docker build -t nginx-less:binary -f handmade-nginx-binary.Dockerfile --progress=plain --no-cache . # verbose
```

### 👋 Interesting System Install Notes
1️⃣
```yaml
- zip is keg-only, which means it was not symlinked into /opt/homebrew
- because macOS already provides this software
- installing another version in parallel can cause all kinds of trouble
- 
- If you need to have zip first in your PATH, run:
  - echo 'export PATH="/opt/homebrew/opt/zip/bin:$PATH"' >> ~/.zshrc
```
2️⃣
```yaml
- curl is keg-only, which means it was not symlinked into /opt/homebrew
- because macOS already provides this software
- installing another version in parallel can cause all kinds of trouble
- 
- If you need to have curl first in your PATH, run:
  - echo 'export PATH="/opt/homebrew/opt/curl/bin:$PATH"' >> ~/.zshrc
-
- For compilers to find curl you may need to set:
  - export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
  - export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
-
- For pkg-config to find curl you may need to set:
  - export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig"
```

### 👋 Spack 
```yaml
- https://spack.readthedocs.io/en/latest/getting_started.html # debugging # advanced
- https://spack.readthedocs.io/en/latest/basic_usage.html # debugging # advanced
```
