### DISCUSSION TITLE
Foundation: Build Systems

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#38] [Explore / Experiment]
### Deep Dive - 0
- Do a deep dive of following & come out with workshops for each of these tools:
  - https://github.com/teamniteo/nix-docker-base
  - https://github.com/LnL7/nix-docker
  - https://github.com/nlewo/nix2container
  - https://github.com/nix-community/docker-nixpkgs
  - https://github.com/tazjin/nixery/blob/master/default.nix
  - https://github.com/3noch/nix-bundle-exe
  - https://github.com/matthewbauer/nix-bundle
  - https://github.com/fzakaria/shrinkwrap
  - https://github.com/fzakaria/sqlelf
  - https://github.com/tazjin/nixery
  - https://github.com/chainguard-dev/apko

### Deep Dive - 1
- Build: Minimal Nginx using Nix

### Backlog
- Build: C++ app using Nix
  - Refer: https://github.com/tfc/nix_cmake_example
- Build: 
  - Envoy
  - Kong
  - https://github.com/opencontainers/runc/releases/tag/v1.1.5
- Workshop: https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support

### Master Quotes
```yaml
- https://dev.to/vito/why-i-joined-dagger-43gb
  - Reproducible builds: **HOLY GRAIL** of CI/CD
  - Guarantee: Every run produces bit-for-bit identical outputs
  - Hence accounts for every single input
    - Including [time](https://bass-lang.org/bassics.html#s2.4p14) itself! 
  - Another adjective for this type of build is **HERMETIC** 👈
```

```yaml
- Hermetic implies holy grail. How?
  - Hermetic builds UNLOCK a lot of COOL IDEAS 🎁 😇
  - Allows:
    - Aggressive CACHING
    - DEDUP concurrent runs
    - Allow artifact RECIPES to be published ALONGSIDE the ARTIFACT itself
    - Thus act as a “PROOF of its CHECKSUM" 😍 🙇‍♀️
  - Prevent surprises in the path to production
    - Everyone see the same thing i.e. same in dev machines vs CI machines
```

**Comment by AmitKumarDas** [comment]
### Golang / Tracing / Profiling / Dependency / Tooling
```yaml
- https://proxy.golang.org/
  - # a module mirror for accelerating Go module downloads
  - # an index for discovering new modules
  - # a global go.sum database for authenticating module content
  - 
- https://github.com/containerd/cgroups/pull/275 # allocation # performance # parca
- https://www.polarsignals.com/blog/posts/2023/03/28/how-to-read-icicle-and-flame-graphs/ # basics
- https://pkg.go.dev/golang.org/x/exp/cmd/modgraphviz # dependency
- https://pkg.go.dev/golang.org/x/tools/cmd/digraph # DAG # dependency
- https://github.com/cashapp/hermit # package static binary # like bingo perhaps
- https://github.com/alecthomas/participle # define any parser in Go # grammar # ast # lexer # token
- https://dzone.com/articles/how-we-solved-an-oom-issue-in-tidb-with-gomemlimit # GOMEMLIMIT
```

**Comment by AmitKumarDas** [comment]
### Other Languages / Compiler

```yaml
- https://tweedegolf.nl/en/blog/88/data-oriented-design
- https://github.com/rui314/chibicc # literate programming # learn from commits
- https://github.com/rui314/mold # linker # vs LLVM lld # GNU gold
- https://www.openmymind.net/Zig-Quirks/ # zig
- https://perso.crans.org/vanille/treebor/ # rust # alias model
- https://maximullaris.com/awk_tech_notes.html # awk
- https://matklad.github.io/2023/03/26/zig-and-rust.html # zig # rust
```

**Comment by AmitKumarDas** [comment]
#### Spack
```yaml
- spack info --phases nginx # preferred vs safe versions # build vs run vs link dependencies
- Research: https://buildsi.github.io/build-notes/ 🔥 # fellow # CFP?
- Origins: Originally from LLNL and for the supercomputing community
- Provides a meta build system to orchestrate installation of software stacks
- View Area: 🎯
  -  spack view add ~/opt/spack-emacs emacs
  - ~/opt/spack-emacs/bin/emacs --version
  - ls ~/opt/spack-emacs/lib | wc -l
  - echo -n $LD_LIBRARY_PATH|tr : ’\n’|wc -l
  - No need to “pollute” shell env. vars. to use a view
  - Instead we pollute a directory!
  - Automatically add/remove files from one or more packages + their dependencies
  - Files added via symlink, hardlink or copy. View directories are always real, not linked
  - Can also install your own non-Spack builds into a Spack view 😍
- Features:
  - Bundle Packages: collects (only) dependencies on other packages
  - Environments: group specs, associate views, freeze package.py’s
  - Containers: generate container build recipes based on an Environment
  - Relocation: 🔥
    - enable build cache and binary packages to allow move of binary installations by updating RPATH and #! lines
  - Configuration Scopes: isolate in levels of system/site/user/custom
  - Chaining: supports managing a diversity of many Spack installations
  - Extensions: 
    - write Python code using Spack internals, provides Spack commands
    - maybe as a precursor to contributing to Spack!
- Typically RPATH is baked in so executables always find their libs 🔥
- "spack load" will strongly populate PATH-like variables
  - echo $LD_LIBRARY_PATH|tr : ’\n’|wc -l
- wc -l spack/var/spack/repos/builtin/packages/{sed,emacs,root,python}/package.py
- spack list|wc -l
- spack list emacs
- spack spec emacs
- spack find -l emacs
- ls $(spack location -i emacs/5y)/bin
- overlay as may repositories as you want
- spack install emacs @27.1
- spack install emacs @27.1 %clang
- spack install emacs @27.1 %clang ^openssl@1.1.1f
- Getting Started:
  - # git clone 
  - # . spack/share/spack/setup-env.sh
  - # echo $PATH
- Uses clingo to resolve OPTIMAL versions and variants of dependencies when installing a package
- clingo itself is a binary, Spack has to install it on initial use # bootstrapping
- https://www.phy.bnl.gov/~bviren/tmp/npps/spack-tour.pdf # quote # unquote
- Not a REPLACEMENT for language package & build system
- Not 100% hermetic build
  - relies on some low-level host OS libs (eg libc, libm, libdl)
- Package repo + concrete spec = fully-determined build output
  - Not at Nix level i.e. Not 100% bit perfect deterministic
- Not an OS level package system # does not need ROOT permissions
- Repos are vehicles to collaborate on packaging
```

#### Guix
```yaml
- https://guix.gnu.org/en/blog/2023/dissecting-guix-part-2-the-store-monad/
- https://guix.gnu.org/en/blog/2023/building-toolchains-with-guix/
- https://github.com/NixOS/nixpkgs/pull/43221
- 
```

#### Bazel
```yaml
- https://jayconrod.com/posts
- https://github.com/bazelbuild/examples/tree/main/bzlmod
- https://github.com/bazelbuild/bzlmod/tree/main/fetch
```

#### Build Related
```
- https://nickdesaulniers.github.io/blog/2018/06/02/speeding-up-linux-kernel-builds-with-ccache/ # ccache
- https://github.com/bazelbuild/examples
- https://github.com/envoyproxy/envoy/issues/19535 # zig build system # bazel
- https://cone.codes/posts/using-zig-to-build-native-lua-scripts/ # zig build system # lua
- https://github.com/containerd/stargz-snapshotter # fast distribution # lazy pulling # container
- https://github.com/ostreedev/ostree-rs-ext/ # chunk # layer # image # container
- https://lwn.net/Articles/905164/ # container # docker # history # landscape
- https://github.com/containerd/nerdctl # Compose # Rootless # eStargz # OCIcrypt # IPFS
- https://lwn.net/Articles/902049/ # docker # vs Podman # vs OCI # CRI-O # vs Containerd # Internals
- https://lwn.net/Articles/821367/ # merkle tree # build system # ostree # ninja
- https://mail.gnome.org/archives/buildstream-list/2018-April/msg00006.html # buildstream # remote execution
- https://docs.google.com/document/d/1AaGk7fOPByEvpAbqeXIyE8HX_A3_axxNnvroblTZ_6s/edit # CAS # Bazel # Remote Execution API
- https://blog.orhun.dev/alpine-packaging-setup/ # apk # chroot # patch
```
