### DISCUSSION TITLE
Explore Nix / DevEx

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#7] [Explore / Experiment]
```yaml
- Uninstall Nix
  - Delete the Nix store (and misc. Nix-related files) as root: rm -rf /nix/
  - Delete the Nix configuration file as root: rm -rf /etc/nix
  - Delete your user links as normal user: rm -rf ~/.nix-channels ~/.nix-defexpr ~/.nix-profile
  - refer: https://nix-tutorial.gitlabpages.inria.fr/nix-tutorial/installation.html
- Worked in Mac
  - sudo vifs & comment the line
  - diskutil apfs deleteVolume "Nix Store"
  - Remove the 'nix' line from /etc/synthetic.conf or the file"
  - refer: https://github.com/NixOS/nix/issues/3900
```

```yaml
- flox
- https://floxdev.com/blog/flox-open-beta
- https://github.com/flox/flox
  - Environments with wings
  - With isolated, portable environments, you can run different versions of any program without fear of breaking your system
  - You can swap in or out of any environment, seamlessly switching contexts with perfect isolation
  - No need for cloud VMs, or shared terminal sessions–everyone recreates the same bits on their machines and is free to start coding with minimal setup hassle
  - Render your environment as a container runtime for use with Docker, Kubernetes, or publish your artifact to the flox Catalog
```
