### DISCUSSION TITLE
Passion: Languages, Compilers, Runtimes & more

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/buildit#9] [Explore / Experiment]
```yaml
- https://github.com/ostreedev/ostree-releng-scripts
- https://github.com/opensbom-generator/parsers
- https://github.com/nishakm/genv
- https://github.com/cve-search/git-vuln-finder
- https://diffoscope.org/
- https://github.com/bureado/awesome-software-supply-chain-security
- The Little Schemer Book
- https://acha.ninja/
- https://words.filippo.io/efficient-go-apis-with-the-inliner/
- https://web.cs.wpi.edu/~jshutt/kernel.html
- http://ratfactor.com/now
- http://ratfactor.com/forth/forth_talk_2023.html
- https://prog21.dadgum.com/
- https://vale.dev/
- https://craftinginterpreters.com/introduction.html
- https://justine.lol/sectorlisp2/
- https://justine.lol/sectorlisp/lisp-history.pdf
- https://justine.lol/sectorlisp2/aimemo8.txt
- Austral
- Unison
- Roc
- Hare
- https://www.plover.com/~mjd/misc/hbaker-archive/ForthStack.html
- https://borretti.me/article/
- https://drewdevault.com/
- https://harelang.org/blog/
- https://c9x.me/compile/doc/il.html
- https://github.com/google/sanitizers/wiki/AddressSanitizerAlgorithm
- https://gist.github.com/nicknapoli82/30f1c7b30e7b1561026d88655e5278f7 # Everything in C is Ptr
- https://sr.ht/~autumnull/haredo/
```

**Comment by AmitKumarDas** [comment]
### Go's MID STACK INLINER

```yaml
- RETURN fresh BYTE SLICE i.e. []byte
- Escape analysis MOVES it to the HEAP
- 💰 Heap allocations are EXPENSIVE 
- 🐌 Heap allocations put PRESSURE on the garbage collector (GC)
- 
- benchstat <(gotip test -bench Sign -benchmem -count 10 crypto/ed25519)
- 
- PASSING NIL can ALLOCATE 💰
- Instead try SLICING to ZERO i.e. slice[:0]
- 
- MID STACK INLINER
- go build -gcflags -m x25519.go
- func NewFoo() *Foo constructors can take advantage of MID STACK INLINER
- So go build APIs that return a new value without forcing a heap allocation
- 
- refer: https://words.filippo.io/efficient-go-apis-with-the-inliner/
```

**Comment by AmitKumarDas** [comment]
### JuNest
- https://github.com/fsquillace/junest

```yaml
- JuNest Does Not:
  - Build isolated environments (like Docker or Vagrant)
- JuNest Enables:
  - Running programs as if they were running natively from the host OS
```

```yaml
- What: Similarity with Dockerfile
- Ans: JuNest uses package manager (pacman)
```

```yaml
- What: Is shared between Host OS & JuNest sandbox?
- Ans: Almost everything
  - kernel, process subtree, network, mounting, etc.
```

```yaml
- Why: Only the ROOT filesystem is ISOLATED
- Ans: Since the programs installed in JuNest need to reside elsewhere
```

```yaml
- Why: Use JuNest
- Ans:
  - Create disposable and partially isolated GNU/Linux environments
  - Install packages without root privileges
  - Install packages inside them without risking mishaps on production systems
  - Run on a different architecture from the host OS via QEMU
- Sample:
  - E.g. Install the top command in JuNest 
  - And use it to monitor processes belonging to the host OS
  - JuNest allows interaction between processes belonging to both host OS and JuNest
```

**Comment by AmitKumarDas** [comment]
### Merkle trees & Build system
- https://lwn.net/Articles/821367/

```yaml
- Idea: 
  - An entire tree (directory) as a dependency
```

```yaml
- OSTree:
  - Similar to Git
  - Can store entire filesystem images such as a complete Linux system
  - More metadata about files than Git
  - To build and roll-out software updates to Linux-based devices
  - Like Git, OSTree stores files in a "Content Addressable Store" 🎯
  - I.e. Can retrieve the contents of a file if checksum of those contents is known
  - File ownership, permissions, and xattrs are also reflected in the checksum
  - References are how OSTree implements branches and tags
  - A ref is a metadata file in the OSTree repository
  - Metadata filename can be anything (analogy to git branch or tag name)
  - And its content is a single SHA pointing at a tree
```

```yaml
- Ninja:
  - Does not support wildcards or loops
  - Build targets and inputs are files
  - OSTree refs are also files
  - When you run ninja in an incremental build, if any of the input refs changes
    - Remember, a ref contains a SHA pointing at a tree
  - So if any file in the tree changes then the ref's content will change
  - So Ninja concludes the rootfs target is outdated & the rule needs to be re-run
```

```yaml
- Ninja + OSTree = Build System:
  - Toolchains and build environments can be managed explicitly
  - Rule to compile something can take a "build root" rootfs as one of its dependencies
  - Then chroot into it to run the compilation command
    - Above is known as hermetic builds
  - This build rootfs can itself be created by other rules
  - A build system that can define a dependency that is a subtree of a previous target
    - Could specify separate rules for these operations
    - Run them in parallel
    - Farm out the execution of individual build steps to remote build servers
  - And then merge the results back into a final rootfs tree
- Protip:
  - You should commit the build artifacts to an OSTree repository
  - CI can run ostree diff on each pull request
  - Devs can see exactly which files changed in the output rootfs
  - Gaining confidence in the correctness of the incremental builds
```

**Comment by AmitKumarDas** [comment]
### 💯 apt2ostree: Build System for Debian/Ubuntu packages
- https://github.com/stb-tester/apt2ostree
- OSTree + Ninja

```yaml
- What:
- Builds Debian/Ubuntu based ostree images
- Builds the output as an ostree tree instead of rootfs in a directory
```

```yaml
- Features:
  - Fast, Reproducible, Space efficient
  - No dependency on apt/dpkg
  - Build multiple similar but different images
  - Version-control package updates like source code
```

```yaml
- Reproducible Packages: 👋 I need this 😎
  - Perform dependency resolution from a list of packages 
  - Generate a "lockfile" listing all packages, their versions and their SHAs
  - Commit this lockfile to git
  - Builds from this lockfile are functionally reproducible
```

```yaml
- Fast Builds:
  - Download and extract any given deb ONCE (across multiple images)
  - This saves disk space since the CONTENTS of the debs are COMMITED to ostree
  - So they will share disk space with the built images
  - COMBINING the contents of the debs is FAST
    - It only touches ostree metadata
    - It doesn't need to read the contents of the files
  - Ninja plays its part
    - Does not repeat already built work
    - Builds happen in parallel
```

```yaml
- Reproducibility via Lockfile:
- apt:
  - apt is designed to keep traditional systems up-to-date
  - apt-mirrors do not keep old packages in their indices
- lockfile:
  - leaf from modern programming language package managers
- Two files: 
  - first file is updated with list of packages
  - second one is generated from first
  - second one has the packages with their versions & all their transitive dependencies
  - this second file is the lockfile
```

```yaml
- Localfile Format:
  - Is same as Debian Package Index as used by apt
  - https://wiki.debian.org/DebianRepository/Format#A.22Packages.22_Indices
```

```yaml
- Lockfile Contents:
  - MD5, SHA1, SHA256
    - Gives certainty without being overly dependent on GPG
  - URL
    - Enables downloading packages
```

```yaml
- How does DETERMINISM / PINNING help:
  - Enables travelling back to a particular revisions & building the same
  - Recorded in git via Lockfiles
  - Hence security updates are RECORDED & MANAGED & DEPLOYED explicitly
```

**Comment by AmitKumarDas** [comment]
### aptly - Debian Repository Management Tool
- https://github.com/aptly-dev/aptly

**Comment by AmitKumarDas** [comment]
### Good Reads on Shell
```yaml
- https://www.oilshell.org/blog/
- https://www.t-ravis.com/post/shell/no_look_no_leap_shell_with_nix/
- https://j3s.sh/thought/write-posix-shell.html
- https://www.zombiezen.com/blog/2023/03/connecting-bash-to-nix/
```

**Comment by AmitKumarDas** [comment]
### Redo: Build Systems

```yaml
- What: Is so great about Redo?
- Ans:
  - A simple set of primitives executed via the shell
  - Redo primitives (build scripts) can be written in any language
  - Redo is tiny!
  - Redo can integrate seamlessly in any build system or wrap them
  - Redo supports checksumming of targets, not just mtime
- Refer:
  - https://fzakaria.com/2020/06/08/my-love-letter-to-redo.html
```

```yaml
- What: mtime (modified time) comparison considered harmful
- Notes: 
  - directory, tree, traversal, inode numbers, filenames, ctime
  - file ownership, size, hardlink, atime
  - precision, not monotonically increasing, 
  - newly created file can be timestamped in the past or in the future,
  - mtime vs checksums w.r.t deployment to containers
- Refer: https://apenwarr.ca/log/20181113
```

```yaml
- What: Go compiler reads & hashes the input files
- Refer: https://github.com/golang/go/commit/7dea509703eb5ad66a35628b12a678110fbb1f72
```
