### ISSUE TITLE
My Sprint Planning & Progress

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/buildit#39]
### Backlog
```yaml
- What: Unpack nixpkgs DockerTools to Nix-101 | Script-101
- Source: https://github.com/NixOS/nixpkgs/commits/master/pkgs/build-support/docker
- Tag: Sticky

- What: Unpack cachix to Nix
- Source: https://github.com/cachix
- Tag: Sticky, GH Actions

- What: Unpack Determinate Systems to Nix
- Source: https://github.com/DeterminateSystems
- Tag: Sticky, GH Actions

- What: Unpack Containers
- Source: The internals and the latest trends of container runtimes (2023) | by Akihiro Suda | nttlabs | Jun, 2023 | Medium
- Source: https://medium.com/nttlabs/the-internals-and-the-latest-trends-of-container-runtimes-2023-22aa111d7a93

- What: Real World Use Case for Nix
- What: Nix, Docker Container, Image, Envoy, Docker Manifest, gRPC
- Source: https://github.com/mirkolenz/flocken/tree/main
- Source: https://www.reddit.com/r/NixOS/comments/14by1fm/create_multiarch_docker_images_with_nix/
- Source: https://github.com/mirkolenz/grpc-proxy
```

```yaml
- What: Unpack Envoy builds via containers
- Source: https://github.com/envoyproxy/envoy/tree/main/ci
- Dest: https://github.com/AmitKumarDas/buildit/blob/main/build/nix/literate/0-Unpack-Envoy.md

- What: Merge Distroless & Distroless commits & fill Bazel 101
- Where: https://github.com/AmitKumarDas/buildit/blob/main/build/nix/literate/0-Unpack-Distroless-Commits.md
- Dest: https://github.com/AmitKumarDas/buildit/blob/main/build/nix/literate/0-Unpack-Distroless.md

- What: Unpack Distroless commits & fill Bazel 101

- What: Unpack Bazel & Nix space game repo
- Dest: https://github.com/AmitKumarDas/buildit/blob/main/build/nix/literate/0-Unpack-Bazel-Nix-Space-Game.md
 
- What: Unpack FRSCA
- Source: https://github.com/buildsec/frsca
```

```yaml
- What: Content Addressed paths in Nix
- Source: https://github.com/tweag/rfcs/blob/cas-rfc/rfcs/0062-content-addressed-paths.md
- Source: https://edolstra.github.io/pubs/phd-thesis.pdf
- Source: https://www.tweag.io/blog/2021-12-02-nix-cas-4/

- What: Unpack Nixery
- Source: https://github.com/tazjin/nixery
 
- What: Nix binary cache substitution
- Source: https://flokli.de/posts/2021-12-10-nix-casync-intro/
- 
- What: Unpack divnix book on Nix to Nix 101
- Source: https://book.divnix.com/ch05-01-language-basics.html
- 
- What: Unpack reproducible examples:
- Source: https://github.com/mlieberman85/reproducible-examples
- Source: https://github.com/kpcyrd/i-probably-didnt-backdoor-this
- 
- What: Distributed trust & reproducibility tracking for binary caches
- Source: https://github.com/nix-community/trustix
- 
- What: A nix flake for many AI projects
- Source: https://github.com/nixified-ai/flake
- Why: This might help in building development environments
- 
- What: Unpack binfmt
- Source: https://github.com/tonistiigi/binfmt
- 
- What: Unpack rootlesskit
- Source: https://github.com/rootless-containers/rootlesskit/
- 
- [🌱] What: Pass OCI conformance tests for `crane registry server`
- Source: https://github.com/google/go-containerregistry/issues/1661
- 
- [🌱] What: Load OCI layout directories
- Source: https://github.com/dagger/dagger/pull/5363
- Why: Useful to build container images minus Docker
- 
- [ ] What: OCI publish/export format to OCI 101
- Source: https://github.com/dagger/dagger/pull/5365
```
